import io.gitlab.arturbosch.detekt.Detekt
import io.gitlab.arturbosch.detekt.DetektGenerateConfigTask
import io.gitlab.arturbosch.detekt.extensions.DetektExtension
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.artifacts.MinimalExternalModuleDependency
import org.gradle.api.provider.Provider
import org.gradle.kotlin.dsl.DependencyHandlerScope
import org.gradle.kotlin.dsl.apply
import org.gradle.kotlin.dsl.configure
import org.gradle.kotlin.dsl.dependencies
import org.gradle.kotlin.dsl.withType
import org.jetbrains.kotlin.gradle.plugin.KotlinBasePlugin
import ru.pavlig43.convention.extension.libs

class DetektPlugin : Plugin<Project> {
    override fun apply(target: Project) {

        target.plugins.withType(KotlinBasePlugin::class.java) {
            with(target) {

                apply(plugin = libs.plugins.detekt.get().pluginId)

                extensions.configure<DetektExtension>() {

                    config.setFrom(rootProject.files("default-detekt-config.yml"))
                    buildUponDefaultConfig = false
                    autoCorrect = true
                    parallel = true
                    ignoreFailures = true

                }
                with(tasks) {
                    withType<Detekt> {

                        exclude {
                            it.file.invariantSeparatorsPath.contains("/build/generated/")
                        }

                        reports {
                            html.required.set(true)
                            md.required.set(true)

                        }
                    }
                    withType<Detekt>().configureEach {
                        jvmTarget = libs.versions.java.get()
                    }
                    withType<DetektGenerateConfigTask>().configureEach {
                        enabled = false
                    }
                }

                dependencies {
                    detektPlugins(libs.detekt.formatting)

                }
                pluginManager.withPlugin(libs.plugins.pavlig43.compose.get().pluginId) {
                    dependencies {
                        detektPlugins(libs.detekt.compose)
                    }
                }
                pluginManager.withPlugin(libs.plugins.pavlig43.decompose.get().pluginId) {
                    dependencies {
                        detektPlugins(libs.detekt.decompose)
                    }
                }

                // Register task to install git hooks (only in root project)
                if (this == rootProject) {
                    tasks.register("installGitHooks") {
                        group = "development"
                        description = "Installs pre-commit git hook for Detekt"

                        val hooksDir = rootProject.layout.projectDirectory.dir(".git/hooks")
                        val preCommitScript = if (System.getProperty("os.name").lowercase().contains("windows")) {
                            rootProject.layout.projectDirectory.file("scripts/pre-commit.ps1")
                        } else {
                            rootProject.layout.projectDirectory.file("scripts/pre-commit")
                        }

                        inputs.file(preCommitScript)
                        outputs.dir(hooksDir)

                        doLast {
                            val hookFile = hooksDir.file("pre-commit").asFile

                            // Copy appropriate hook script based on OS
                            if (System.getProperty("os.name").lowercase().contains("windows")) {
                                // For Windows: create a wrapper that calls PowerShell script
                                val psScript = rootProject.layout.projectDirectory.file("scripts/pre-commit.ps1").asFile
                                if (psScript.exists()) {
                                    hookFile.writeText(
                                        """
                                        #!/bin/sh
                                        # Generated by Gradle installGitHooks task
                                        powershell.exe -ExecutionPolicy Bypass -File "${psScript.absolutePath.replace("\\", "/")}"
                                        exit $?
                                        """.trimIndent()
                                    )
                                    hookFile.setExecutable(true)
                                    println("✅ Git pre-commit hook installed (Windows)")
                                } else {
                                    println("⚠️  PowerShell script not found at: ${psScript.absolutePath}")
                                }
                            } else {
                                // For Unix-like systems: use bash script
                                val bashScript = rootProject.layout.projectDirectory.file("scripts/pre-commit").asFile
                                if (bashScript.exists()) {
                                    bashScript.copyTo(hookFile, overwrite = true)
                                    hookFile.setExecutable(true)
                                    println("✅ Git pre-commit hook installed (Unix)")
                                } else {
                                    println("⚠️  Bash script not found at: ${bashScript.absolutePath}")
                                }
                            }
                        }
                    }

                    // Make build task depend on installGitHooks (one-time setup)
                    tasks.named("build") {
                        dependsOn("installGitHooks")
                    }
                }
            }
        }
    }
}
private fun DependencyHandlerScope.detektPlugins(dependency: Provider<MinimalExternalModuleDependency>){
    add("detektPlugins",dependency)
}
