plugins {
    // this is necessary to avoid the plugins to be loaded multiple times
    // in each subproject's classloader
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.android.kotlin.multiplatform.library) apply false
    alias(libs.plugins.composeMultiplatform) apply false
    alias(libs.plugins.composeCompiler) apply false
    alias(libs.plugins.kotlinJvm)
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.ksp) apply false
    alias(libs.plugins.room) apply false
    alias(libs.plugins.sqldelight) apply false
    alias(libs.plugins.kotlinx.serialization) apply false
    alias(libs.plugins.buildkonfig) apply false
    alias(libs.plugins.composeHotReload) apply false
    alias(libs.plugins.detekt) apply false
    alias(libs.plugins.dokka)


    //    build-logic
    alias(libs.plugins.pavlig43.kmplibrary) apply false
    alias(libs.plugins.pavlig43.serialization) apply false
    alias(libs.plugins.pavlig43.coroutines) apply false
    alias(libs.plugins.pavlig43.koin) apply false
    alias(libs.plugins.pavlig43.ktor) apply false
    alias(libs.plugins.pavlig43.feature) apply false
    alias(libs.plugins.pavlig43.sqldelight) apply false
    alias(libs.plugins.pavlig43.decompose) apply false
    alias(libs.plugins.pavlig43.detekt) apply false



}

    dokka {
        dokkaPublications.html {
            moduleName.set(project.name)
            moduleVersion.set(project.version.toString())
            // Standard output directory for HTML documentation
            outputDirectory.set(layout.buildDirectory.dir("dokka/html"))
            failOnWarning.set(false)
            suppressInheritedMembers.set(false)
            suppressObviousFunctions.set(true)
            offlineMode.set(false)
            includes.from("packages.md", "extra.md")

            // Output directory for additional files
            // Use this block instead of the standard when you
            // want to change the output directory and include extra files
            outputDirectory.set(rootDir.resolve("docs/api/0.x"))

            // Use fileTree to add multiple files
            includes.from(
                fileTree("docs") {
                    include("**/*.md")
                }
            )
        }


    }

subprojects {
    if (!path.contains("sampletable")) {
        apply(plugin = "pavlig43.detekt")
        tasks.register("detektAll") {
            group = "custom"
            val detektTasks = listOf(
                "detektAndroidDebug",
                "detektDesktopMain",
                "detektMetadataCommonMain",
                "detektMetadataMain"
            ).mapNotNull { tasks.findByName(it) }
            dependsOn(detektTasks)
        }
    }
}

// Git hooks disabled - pre-commit hooks removed
/*
// Root task for installing git hooks
tasks.register("installGitHooks") {
    group = "development"
    description = "Installs pre-commit git hooks"

    doLast {
        val hooksDir = rootProject.layout.projectDirectory.dir(".git/hooks")
        val preCommitHook = hooksDir.file("pre-commit").asFile

        // Copy appropriate hook script based on OS
        if (System.getProperty("os.name").lowercase().contains("windows")) {
            // For Windows: create a wrapper that calls PowerShell script
            val psScript = rootProject.layout.projectDirectory.file("scripts/pre-commit.ps1").asFile
            if (psScript.exists()) {
                preCommitHook.writeText(
                    """
                    #!/bin/sh
                    # Generated by Gradle installGitHooks task
                    powershell.exe -ExecutionPolicy Bypass -File "${psScript.absolutePath.replace("\\", "/")}"
                    exit $?
                    """.trimIndent()
                )
                preCommitHook.setExecutable(true)
                println("✅ Git pre-commit hook installed (Windows)")
            } else {
                println("⚠️  PowerShell script not found at: ${psScript.absolutePath}")
            }
        } else {
            // For Unix-like systems: use bash script
            val bashScript = rootProject.layout.projectDirectory.file("scripts/pre-commit").asFile
            if (bashScript.exists()) {
                bashScript.copyTo(preCommitHook, overwrite = true)
                preCommitHook.setExecutable(true)
                println("✅ Git pre-commit hook installed (Unix)")
            } else {
                println("⚠️  Bash script not found at: ${bashScript.absolutePath}")
            }
        }

        println("")
        println("Pre-commit hook will run:")
        println("  1. Detekt formatting (autoCorrect)")
        println("  2. Detekt checks")
        println("")
        println("To skip hooks temporarily, use: git commit --no-verify")
    }
}

// Auto-install hooks on first build
tasks.register("checkAndInstallGitHooks") {
    group = "development"
    description = "Checks if git hooks are installed and installs them if not"

    doLast {
        val hookFile = rootProject.layout.projectDirectory.file(".git/hooks/pre-commit").asFile
        if (!hookFile.exists()) {
            println("")
            println("⚠️  Git hooks not found. Installing automatically...")
            println("")
            tasks.named("installGitHooks").get().actions.forEach { it.execute(this) }
        } else {
            // Check if hook is up to date (contains our marker)
            val hookContent = hookFile.readText()
            if (!hookContent.contains("Generated by Gradle installGitHooks task")) {
                println("")
                println("⚠️  Git hooks outdated. Updating...")
                println("")
                tasks.named("installGitHooks").get().actions.forEach { it.execute(this) }
            }
        }
    }
}

// Make sure hooks are checked before any build
tasks.named("build") {
    dependsOn("checkAndInstallGitHooks")
}

tasks.named("assemble") {
    dependsOn("checkAndInstallGitHooks")
}
*/

