
@file:Suppress("MagicNumber")

package ru.pavlig43.theme

import androidx.compose.ui.graphics.Color

internal val primaryLight = Color(0xFF1B6585)
internal val onPrimaryLight = Color(0xFFFFFFFF)
internal val primaryContainerLight = Color(0xFFC3E8FF)
internal val onPrimaryContainerLight = Color(0xFF004C68)
internal val secondaryLight = Color(0xFF4E616D)
internal val onSecondaryLight = Color(0xFFFFFFFF)
internal val secondaryContainerLight = Color(0xFFD1E5F4)
internal val onSecondaryContainerLight = Color(0xFF364955)
internal val tertiaryLight = Color(0xFF605A7D)
internal val onTertiaryLight = Color(0xFFFFFFFF)
internal val tertiaryContainerLight = Color(0xFFE6DEFF)
internal val onTertiaryContainerLight = Color(0xFF484264)
internal val errorLight = Color(0xFFBA1A1A)
internal val onErrorLight = Color(0xFFFFFFFF)
internal val errorContainerLight = Color(0xFFFFDAD6)
internal val onErrorContainerLight = Color(0xFF93000A)
internal val backgroundLight = Color(0xFFF6FAFE)
internal val onBackgroundLight = Color(0xFF171C1F)
internal val surfaceLight = Color(0xFFF6FAFE)
internal val onSurfaceLight = Color(0xFF171C1F)
internal val surfaceVariantLight = Color(0xFFDCE3E9)
internal val onSurfaceVariantLight = Color(0xFF41484D)
internal val outlineLight = Color(0xFF71787D)
internal val outlineVariantLight = Color(0xFFC0C7CD)
internal val scrimLight = Color(0xFF000000)
internal val inverseSurfaceLight = Color(0xFF2C3134)
internal val inverseOnSurfaceLight = Color(0xFFEDF1F5)
internal val inversePrimaryLight = Color(0xFF8FCFF3)
internal val surfaceDimLight = Color(0xFFD6DADF)
internal val surfaceBrightLight = Color(0xFFF6FAFE)
internal val surfaceContainerLowestLight = Color(0xFFFFFFFF)
internal val surfaceContainerLowLight = Color(0xFFF0F4F8)
internal val surfaceContainerLight = Color(0xFFEAEEF2)
internal val surfaceContainerHighLight = Color(0xFFE5E9ED)
internal val surfaceContainerHighestLight = Color(0xFFDFE3E7)


internal val primaryDark = Color(0xFF8FCFF3)
internal val onPrimaryDark = Color(0xFF003549)
internal val primaryContainerDark = Color(0xFF004C68)
internal val onPrimaryContainerDark = Color(0xFFC3E8FF)
internal val secondaryDark = Color(0xFFB5C9D7)
internal val onSecondaryDark = Color(0xFF20333D)
internal val secondaryContainerDark = Color(0xFF364955)
internal val onSecondaryContainerDark = Color(0xFFD1E5F4)
internal val tertiaryDark = Color(0xFFCAC1EA)
internal val onTertiaryDark = Color(0xFF312C4C)
internal val tertiaryContainerDark = Color(0xFF484264)
internal val onTertiaryContainerDark = Color(0xFFE6DEFF)
internal val errorDark = Color(0xFFFFB4AB)
internal val onErrorDark = Color(0xFF690005)
internal val errorContainerDark = Color(0xFF93000A)
internal val onErrorContainerDark = Color(0xFFFFDAD6)
internal val backgroundDark = Color(0xFF0F1417)
internal val onBackgroundDark = Color(0xFFDFE3E7)
internal val surfaceDark = Color(0xFF0F1417)
internal val onSurfaceDark = Color(0xFFDFE3E7)
internal val surfaceVariantDark = Color(0xFF41484D)
internal val onSurfaceVariantDark = Color(0xFFC0C7CD)
internal val outlineDark = Color(0xFF8A9297)
internal val outlineVariantDark = Color(0xFF41484D)
internal val scrimDark = Color(0xFF000000)
internal val inverseSurfaceDark = Color(0xFFDFE3E7)
internal val inverseOnSurfaceDark = Color(0xFF2C3134)
internal val inversePrimaryDark = Color(0xFF1B6585)
internal val surfaceDimDark = Color(0xFF0F1417)
internal val surfaceBrightDark = Color(0xFF353A3D)
internal val surfaceContainerLowestDark = Color(0xFF0A0F12)
internal val surfaceContainerLowDark = Color(0xFF171C1F)
internal val surfaceContainerDark = Color(0xFF1C2023)
internal val surfaceContainerHighDark = Color(0xFF262B2E)
internal val surfaceContainerHighestDark = Color(0xFF313539)
